logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

repository:
  external:
    state-of-emergency:
      scheme: https
      host: l1ncqf4mxg.execute-api.ap-northeast-1.amazonaws.com
      port: 443
      path: /dev/stateofemergency
      query: prefecture={prefecture}
