logging:
  level:
    root: INFO

repository:
  external:
    state-of-emergency:
      scheme: https
      host: g8shw1q2ri.execute-api.us-east-2.amazonaws.com
      port: 443
      path: /dev/state_of_emergency
      query: prefecture={prefecture}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/state_of_emergency_db?characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true