logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

repository:
  external:
    state-of-emergency:
      scheme: http
      host: localhost
      port: 8080
      path: /dev/state_of_emergency
      query: prefecture={prefecture}
